#remote_theme: "pmarsceill/just-the-docs"
theme: "just-the-docs"
aux_links:
  "Edit on Github":
    - "//github.com/bcgov/HADF-Overview/"
    
footer_content: "<a href='https://gov.bc.ca/'>
  <img 
    src='assets/images/BCID_H_rgb_pos.png' 
    height='42' 
    width='200' 
    style='display: block; margin-left: auto;margin-right: auto;width: 50%;' 
    alt='BC Gov'/> 
</a>"
